import {
  Home,
  PatientRegistration,
  OPD,
  IPD,
  Pharmacy,
  Radiology,
  Laboratory,
  Billing,
  UserProfile,
} from "../views";

/**
 * list of available routes for the entire application.
 */
export const appRoutes = [
  {
    path: "/home",
    name: "Home",
    roles: ["*"],
    view: true,
    icon: "fa fa-clinic-medical",
    component: Home,
    layout: "/app",
  },
  {
    path: "/registration",
    name: "Registration",
    roles: ["System Developer", "Application: Registers Patients"],
    view: true,
    icon: "fa fa-user-plus",
    component: PatientRegistration,
    layout: "/app",
  },
  {
    path: "/opd",
    name: "OPD",
    roles: ["Organizational: Doctor"],
    view: true,
    icon: "fa fa-user-md",
    component: OPD,
    layout: "/app",
  },
  {
    path: "/ipd",
    name: "IPD",
    roles: ["System Developer"],
    view: true,
    icon: "fa fa-procedures",
    component: IPD,
    layout: "/app",
  },
  {
    path: "/pharmacy",
    name: "Pharmacy",
    roles: ["System Developer"],
    view: true,
    icon: "fa fa-prescription-bottle-alt",
    component: Pharmacy,
    layout: "/app",
  },
  {
    path: "/billing",
    name: "Billing",
    roles: ["Billig"],
    view: true,
    icon: "fa fa-receipt",
    component: Billing,
    layout: "/app",
  },
  {
    path: "/laboratory",
    name: "Laboratory",
    roles: ["Regisration Admin", "Registration Clerk", "Billing"],
    view: true,
    icon: "fa fa-vials",
    component: Laboratory,
    layout: "/app",
  },
  {
    path: "/radiology",
    name: "Radiology",
    roles: ["Regisration Admin", "Registration Clerk", "Billing"],
    view: true,
    icon: "fa fa-x-ray",
    component: Radiology,
    layout: "/app",
  },
  {
    path: "/user-profile",
    name: "User Profile",
    roles: ["*"],
    view: false,
    icon: "",
    component: UserProfile,
    layout: "/app",
  },
];
