export const FETCH_AVATAR = "FETCH_AVATAR";
export const REMVOE_AVATAR = "REMOVE_AVATAR";
export const FETCH_PROVIDERS = "FETCH_PROVIDERS";

//TO DELETE
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";

export const LOADING_LOCATIONS = "LOADING_LOCATIONS"
export const LOCATIONS_LOADED = "LOCATIONS_LOADED"

export const LOADING_VISITS = "LOADING_VISITS"
export const VISITS_LOADED = "VISITS_LOADED"

export const LOADING_PATIENT = "LOADING_PATIENT"
export const PATIENT_LOADED = "PATIENT_LOADED"

export const LOADING_CONCEPTS = "LOADING_CONCEPTS"
export const CONCEPTS_LOADED = "CONCEPTS_LOADED"

export const ENCOUNTER_TYPES_LOADED = "ENCOUNTER_TYPES_LOADED"
export const ENCOUNTER_TYPES_LOADING = "ENCOUNTER_TYPES_LOADING"

export const SAVING_PATIENT_HISTORY = "SAVING_PATIENT_HISTORY"
export const PATIENT_HISOTRY_SAVED = "PATIENT_HISOTRY_SAVED"

export const FETCH_SERVICES = "FETCH_SERVICES";
export const FETCH_APPOINTMENT_BLOCK_WITH_TIME_SLOTS =
  "FETCH_APPOINTMENT_BLOCK_WITH_TIME_SLOTS";
export const ADD_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "ADD_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
export const UPDATE_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "UPDATE_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
export const DELETE_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "DELETE_APPOINTMENT_BLOCK_WITH_TIME_SLOT";