export const FETCH_AVATAR = "FETCH_AVATAR";
export const REMVOE_AVATAR = "REMOVE_AVATAR";
export const FETCH_PROVIDERS = "FETCH_PROVIDERS";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_SERVICES = "FETCH_SERVICES";
export const FETCH_APPOINTMENT_BLOCK_WITH_TIME_SLOTS =
  "FETCH_APPOINTMENT_BLOCK_WITH_TIME_SLOTS";
export const ADD_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "ADD_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
export const UPDATE_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "UPDATE_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
export const DELETE_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "DELETE_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
